
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PARAPERTURA = 21;
  public static final int DOSPUNTOS = 13;
  public static final int CHAR = 10;
  public static final int RES = 25;
  public static final int GRAPHPIE = 35;
  public static final int DOUBLE = 9;
  public static final int DOSPUNTOSSEGUIDOS = 14;
  public static final int GRAPHBAR = 36;
  public static final int CORAPERTURA = 19;
  public static final int TITULOY = 46;
  public static final int TITULOX = 45;
  public static final int EJEY = 44;
  public static final int EJEX = 43;
  public static final int IGUAL = 18;
  public static final int PARCIERRE = 22;
  public static final int COLUMN = 8;
  public static final int ARROBA = 16;
  public static final int TITULO = 40;
  public static final int DIV = 27;
  public static final int ENDPROGRAM = 3;
  public static final int TYPEDEF = 11;
  public static final int MIN = 34;
  public static final int ID = 12;
  public static final int MEDIANA = 30;
  public static final int EOF = 0;
  public static final int ARREGLO = 5;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int MUL = 26;
  public static final int VALUES = 41;
  public static final int MODA = 31;
  public static final int MOD = 28;
  public static final int ASIGNACION = 15;
  public static final int ASIGNACIONINV = 17;
  public static final int VARIANZA = 32;
  public static final int END = 23;
  public static final int SUM = 24;
  public static final int MEDIA = 29;
  public static final int CORCIERRE = 20;
  public static final int EXEC = 42;
  public static final int LABEL = 39;
  public static final int MAX = 33;
  public static final int HISTOGRAM = 38;
  public static final int GRAPHLINE = 37;
  public static final int VAR = 4;
  public static final int PRINT = 7;
  public static final int CONSOLE = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PROGRAM",
  "ENDPROGRAM",
  "VAR",
  "ARREGLO",
  "CONSOLE",
  "PRINT",
  "COLUMN",
  "DOUBLE",
  "CHAR",
  "TYPEDEF",
  "ID",
  "DOSPUNTOS",
  "DOSPUNTOSSEGUIDOS",
  "ASIGNACION",
  "ARROBA",
  "ASIGNACIONINV",
  "IGUAL",
  "CORAPERTURA",
  "CORCIERRE",
  "PARAPERTURA",
  "PARCIERRE",
  "END",
  "SUM",
  "RES",
  "MUL",
  "DIV",
  "MOD",
  "MEDIA",
  "MEDIANA",
  "MODA",
  "VARIANZA",
  "MAX",
  "MIN",
  "GRAPHPIE",
  "GRAPHBAR",
  "GRAPHLINE",
  "HISTOGRAM",
  "LABEL",
  "TITULO",
  "VALUES",
  "EXEC",
  "EJEX",
  "EJEY",
  "TITULOX",
  "TITULOY"
  };
}

